# Site
repository: mab8192/mab8192.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Michael Blum
title: Data Scientist
email: mblum@codazen.com
website: www.mab8192.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  mab8192
linkedin_username: michael-blum-752578104
orcid_username: 0000-0002-1077-6780

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Michael and I'm a junior data scientist at Codazen. In addition to data management and analysis, I also have experience in full-stack web development.

  I am a student at the University of Utah, currently participating in the BS/MS degree program through the School of Computing, where I have the opportunity to work concurrently on my Bachelor's and Master's degrees in computer science. My MS degree has a focus on data science.

  Known programming languages: <mark>Python</mark>, <mark>Java</mark>, <mark>C++</mark>, <mark>C#</mark>, <mark>C</mark>, and <mark>JavaScript</mark>.

  Proficient technologies: <mark>Linux</mark>, <mark>Git</mark>, <mark>AWS (EC2, Elastic Beanstalk)</mark>, <mark>PyTorch</mark>

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Utah
        caption: 2015 - 2022
        sub_title: "MS in Computing: Data Managment and Analysis, BS Computer Science, Minor Physics, Minor Mathematics"
        quote: >
          Founded in 1850, The University of Utah is the flagship institution of higher learning in Utah. The U is the best in the nation for technology commercialization (Milken Institute rankings).
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Codazen
        link: www.codazen.com
        sub_title: Data Scientist
        caption: May 2020 - Present
        quote: >
          A creative technology company that crafts digital experiences and enterprise solutions for global brands.
        description: | # this will include new lines to allow paragraphs
            At Codazen, I work in a team with 2 other data scientists to identify and implement machine learning solutions for many different kinds of business problems. 

            Recently, our work has focused on computer vision and natural language processing applications in order to help our customers improve their branding.

      - layout: left
        title: The University of Utah
        link: www.utah.edu
        sub_title: Undergraduate Researcher
        caption: January 2020 - May 2020
        quote: >
          The Undergraduate Research Opportunities Program (UROP) provides undergraduate students and mentors the opportunity to work together on research or creative projects.
        description: | # this will include new lines to allow paragraphs
            Before beginning my own research, I volunteered as an undergraduate research assistant at the Integrated Multi-Physics (IMP) Lab in the College of Engineering. The head of the lab, Dr. Pania Newell, strongly encouraged me to pursue the UROP program and engage in my own research. Following her suggestion, I applied and was granted the opportunity to conduct my own research through the lab with financial support from the university.

            The IMP lab focuses primarily on nanoscale porous media, such as amorphous silica. The project Dr. Newell and I came up with was an investigation into the coupled effects that fracture orientation and pore size have on amorphous silica at the atomic level. In order to carry out this investigation, I had to quickly learn how to use LAMMPS, a molecular dynamics (MD) simulation software, and OVITO, a MD visualization program.

            As a result of my efforts, I was included as a co-author on two papers, detailed in a later section.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Game of Life
        link: mab8192.github.io/GameOfLife/
        description: | # this will include new lines to allow paragraphs
          I created this project mostly as a way for me to learn the basics of HTML canvas and JavaScript. I enjoy learning about and using cellular automata and Conway's Game of Life is a great place to start!

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image
      ![Trees](/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
