# Site
repository: mab8192/mab8192.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Michael Blum
title: Data Scientist/Software Engineer
email: mblum@codazen.com
website: www.mab8192.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  mab8192
linkedin_username: michael-blum-752578104
orcid_username: 0000-0002-1077-6780

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Michael and I'm a data scientist at Codazen. I work primarily on machine learning and AI applications, though I also have experience in full-stack web development.

  I'm also a graduate student at the University of Utah, currently working on my Master's degree in computer science.

  My best programming language is <mark>Python</mark>, though I'm also very comfortable in <mark>Java</mark>, <mark>C++</mark>, <mark>C#</mark>, <mark>C</mark>, and <mark>JavaScript</mark>.

  With Python in particular, I have professional experience with <mark>PyTorch</mark>, <mark>NumPy</mark>, <mark>SpaCy</mark>, <mark>Scikit-learn</mark>, <mark>Pandas</mark>, and many of the other commonly used packages.

  In addition to those languages, I'm also proficient in the following technologies: <mark>Windows/Linux/Mac</mark>, <mark>Git</mark>, <mark>AWS (EC2, Elastic Beanstalk, S3, RDS, etc.)</mark>, <mark>Azure</mark>, and <mark>Heroku</mark>.

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Utah
        sub_title: |
          MS in Computing: Data Managment and Analysis
        caption: 2021 - 2022
        description: |
          For my Master's degree, I chose to pursue the Data Management and Analysis track. Within this track, there is a separate Data Science option which is the track I am currently working towards. I am taking classes such as <mark>Deep Learning</mark>, <mark>Machine Learning</mark>, <mark>Data Mining</mark>, and many others to help get my machine learning engineering skills as sharp as possible.

      - layout: left
        title: University of Utah
        sub_title: |
          BS Computer Science, Minor Physics
        caption: 2015 - 2021
        description: |
          For my Bachelor's degree, I initially started out as a Physics major. I worked towards that degree for about two years before making the decision to switch to Computer Science. My CS electives included: <mark>Artificial Intelligence</mark>, <mark>Virtual Reality</mark>, <mark>Computer Graphics</mark>, <mark>Robotics</mark>, <mark>Computer Networks</mark>, and <mark>Web Browser Internals</mark>. Of these classes, AI and VR were my two favorites.

  - title: Honors & Awards
    layout: list
    content:
      - layout: left
        title: Dean's List
        caption: 2015 - Present
        description: |
          Awarded to students with at least a 3.5 GPA for any given semester. I have been on the dean's list for every semester that I've attended at the University of Utah.

      - layout: left
        title: Robert R. Johnson Innovation Endowed Scholarship
        caption: 2020 - 2021
        description: |
          Awarded to students identified for performing meaningful research.

      - layout: left
        title: Departmental Tuition Waiver Scholarship
        caption: 2015 - 2022
        description: |
          Awarded to students for academic excellence.

      - layout: left
        title: Partial Honors at Entrance Scholarship
        caption: 2015 - 2022
        description:
          Awarded upon entry to the University of Utah for high school transcript and ACT performance.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Codazen
        link: www.codazen.com
        sub_title: Data Scientist
        caption: May 2020 - Present
        quote: >
          A creative technology company that crafts digital experiences and enterprise solutions for global brands.
        description: |
          At Codazen, I work in a team with 2 other data scientists to identify and implement machine learning solutions for many different kinds of business problems.

          Recently, our work has focused on computer vision and natural language processing applications in order to help our customers improve their branding.

      - layout: left
        title: Integrated Multi-Physics Lab, The University of Utah
        link: https://newell.mech.utah.edu/
        sub_title: Undergraduate Researcher
        caption: January 2020 - May 2020
        quote: >
          The Undergraduate Research Opportunities Program (UROP) provides undergraduate students and mentors the opportunity to work together on research or creative projects.
        description: |
          Before beginning my own research, I volunteered as an undergraduate research assistant at the Integrated Multi-Physics (IMP) Lab in the College of Engineering. The head of the lab, Dr. Pania Newell, strongly encouraged me to pursue the UROP program and engage in my own research. Following her suggestion, I applied and was granted the opportunity to conduct my own research through the lab with financial support from the university.

          The IMP lab focuses primarily on nanoscale porous media, such as amorphous silica. The project Dr. Newell and I came up with was an investigation into the coupled effects that fracture orientation and pore size have on amorphous silica at the atomic level. In order to carry out this investigation, I had to quickly learn how to use LAMMPS, a molecular dynamics (MD) simulation software, and OVITO, a MD visualization program.

          As a result of my efforts, I was included as a co-author on two papers, detailed in a later section.

      - layout: left
        title: Fidelity Investments via Education at Work
        link: www.fidelity.com
        sub_title: Data Operations Associate
        caption: January 2020 - May 2020
        quote: >
          Fidelity helps over 32 million people feel more confident in their most important financial goals, manages employee benefit programs for over 22,000 businesses, and supports more than 13,000 financial institutions with innovative investment and technology solutions to grow their businesses.
        description: |
          Significantly increased the efficiency of multiple teams through the creation of 20+ VBA macros built forsystems automation.
          Researched and fixed data discrepancies.
          Completed quality control audits daily to ensure company standards were met.

  - title: Projects
    layout: list
    content:
      - layout: left
        title: Game of Life
        link: mab8192.github.io/GameOfLife/
        link_text: Check it out
        description: |
          I created this project mostly as a way for me to learn the basics of HTML canvas and JavaScript. I enjoy learning about and using cellular automata, and Conway's Game of Life is a great place to start!

      - layout: left
        title: 2020 Gameday Analytics Challenge - 1st Place
        link: https://eccles.utah.edu/news/congratulations-to-the-winners-of-the-game-day-analytics-challenge/
        link_text: Check it out
        description: |
          The Gameday Analytics Challenge is an annual data analysis event put on by the University of Utah's School of Business. The objective is for the participating students to dig into a bunch of tweets about Super Bowl ads and present on any findings they may encounter.

          When I participated, we were given 500,000 tweets to work with. My team and I dug through the data and constructed a few graphs relating to viewer response (positive/negative), which quarter is the best to advertise during, and which ads were talked about the most and at what times.

      - layout: left
        title: 2019 Information Systems Hackathon - 1st Place
        link: https://eccles.utah.edu/news/is-students-compete-in-the-information-systems-hackathon/
        link_text: Check it out
        description: |
          This event was a special production put on by the University of Utah's School of Business in conjuction with Layton Construction.

          The goal of the event was to sift through over 5 million rows of safety data that Layton Construction had collected and present findings on ways they can help increase worker safety.

  - title: A Little More About Me
    layout: text
    content: |
      Alongside my interests in data science and software engineering, some of my other interests and hobbies are:
      - Rocket League (I play competitively for the University of Utah).
      - Watching movies and TV shows (especially the Marvel Cinematic Universe).
      - Messing around in VR.
      - Game development.
      - Bowling! My personal best is 182, though I haven't hit that in a while. My highest recent score is 163.
      - Tabletop board games.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
